### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by anonimity987** [ignaciocastro/adobe-is-dumb#15]
It was working fine  yesterday but now it no longer works. Unlicensed window starts showing up again

**Comment by anonimity987** [comment]
Using the normal manual update (host edit)
Copied all the domain for both 127 and 0.0.0.0, worked for 2 days and now it has stopped working.

**Comment by anonimity987** [comment]
I copied all the list inside my host file from a.dobe.isdumb.one

Or maybe I am doing it wrong, is there any other software to put the url??

**Comment by ignaciocastro** [comment]
> I copied all the list inside my host file from a.dobe.isdumb.one
> 
> Or maybe I am doing it wrong, is there any other software to put the url??

Hey @anonimity987, please do check [the "Usage" part of the readme](https://github.com/ignaciocastro/adobe-is-dumb?tab=readme-ov-file#usage). There's tons of methods of maintaining your hosts list up to date. Today I pushed a commit with more than 10 new domains and it's live, so please update it from your part and check if you still get the pop up. If you still do, download Fiddler Classic ([web page](https://www.telerik.com/fiddler/fiddler-classic) or [direct link](https://telerik-fiddler.s3.amazonaws.com/fiddler/FiddlerSetup.exe)), open it, open your app and search for a subdomain of .adobe.io, .adobestats.io or anything that links to "/integritychecker/". These will appear as soon as the pop up appears. If you post it here, I can add it to the list.

Thank you

**Comment by jmmontoro** [comment]
I'm getting issues starting today may 14th only on Illustrator. Hosts file is up to date.

**Comment by reiwiler** [comment]
Im getting issues on After Effects, cant find Addobe Genuine Service to undownload, and that list i did it all correctly, restarted pc, but still doesnt work, theres still "SHUT DOWN" 
![image](https://github.com/ignaciocastro/adobe-is-dumb/assets/169842838/64549976-699e-41e4-81e3-21d29c2dc93b)

**Comment by ignaciocastro** [comment]
@jmmontoro, @reiwiler Please try again, I have added four new domains to the list.

**Comment by jmmontoro** [comment]
Not working after updating the list, I'll give it a few hours and a few reboots and let you know.

**Comment by reiwiler** [comment]
ok im trying, im gonna turn on adobe ae for 5 min and see if works. ill tell you my feedback @ignaciocastro

**Comment by reiwiler** [comment]
so far so good, i think its working, but ill keep in mind, and saved this site in case anything happening, but thanks @ignaciocastro  for what youve done, i want you to know i 100% appriciate your work

**Comment by ignaciocastro** [comment]
> Not working after updating the list, I'll give it a few hours and a few reboots and let you know.

If it still doesn't work, please try rebooting your pc. If you still see it, please, download Fiddler Classic, open it, open your app and once you see the pop up, go back to Fiddler and find a domain that has mixed letters and numbers and is followed by ".adobestats.io" (or "adobe.io")

**Comment by jmmontoro** [comment]
>If it still doesn't work, please try rebooting your pc. If you still see it, please, download Fiddler Classic, open it, open your app and once you see the pop up, go back to Fiddler and find a domain that has mixed letters and numbers and is followed by ".adobestats.io" (or "adobe.io")
Found the culprit m8c5gtovwb.adobestats.io

**Comment by ignaciocastro** [comment]
> Found the culprit m8c5gtovwb.adobestats.io Blocked and everything is working now.

It has been added to the list, thank you! This issue will be closed, please open a new one of you need more help
